on:
  push:
    branches:
      - main

jobs:
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            SSR_API_HOST=http://api:8000
            NEXT_PUBLIC_API_HOST=${{ secrets.SERVER_URL }}
            NEXT_PUBLIC_IMAGE_HOST=${{ secrets.SERVER_URL }}
          tags: mjuopperi/sakuva:latest
